AnsiblePower/urls.py
from django.conf.urls import url
from django.contrib import admin
from dashboard.views import Index, Dashboard
from adhoc.views import AdHocList, AdHocDetail, AdHocExecute, AdhocLog, AdhocDelete
from job.views import AnsibleJobList, AnsibleJobDetail, AnsibleJobExecuete, AnsibleJobLog
from ansible_auth.views import Login, Logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', Logout.as_view(), name='logout'),

    url(r'^$', Index.as_view(), name='index'),
    url(r'^dashboard/$', Dashboard.as_view(), name='dashboard'),

    url(r'^adhoc/$', AdHocList.as_view(), name='adhoc_list'),
    url(r'^adhoc/(?P<adhoc_id>[0-9]+)/$', AdHocDetail.as_view()),
    url(r'^adhoc/add/$', AdHocExecute.as_view(), name='adhoc_add'),
    url(r'^adhoc/delete/$', AdhocDelete.as_view(), name='adhoc_delete'),
    url(r'^adhoc/log/$', AdhocLog.as_view(), name='adhoc_log'),

    url(r'^job/$', AnsibleJobList.as_view(), name='job_list'),
    url(r'^job/(?P<job_id>[0-9]+)/$', AnsibleJobDetail.as_view()),
    url(r'^job/add/$', AnsibleJobExecuete.as_view(), name='job_add'),
    # url(r'job/delete/$',An)
    url(r'^job/log/$', AnsibleJobLog.as_view(), name='job_log'),

]

adhoc/models.py
from __future__ import unicode_literals
from django.db import models
from ansible_auth.models import AuthUser

# Create your models here.

class AnsibleAdhoc(models.Model):
    adhoc_name = models.CharField(max_length=45, blank=True, null=True)
    adhoc_pattern = models.CharField(max_length=200, blank=True, null=True)
    adhoc_args = models.CharField(max_length=200, blank=True, null=True)
    start_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField(blank=True, null=True)
    finish = models.IntegerField(blank=True, null=True)
    ansible_module = models.ForeignKey('AnsibleModule', models.DO_NOTHING)
    auth_user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        db_table = 'ansible_adhoc'
        ordering = ['-start_time']


class AnsibleAdhocTask(models.Model):
    task_host = models.CharField(max_length=45, blank=True, null=True)
    start_time = models.DateTimeField(blank=True, null=True)
    end_time = models.DateTimeField(blank=True, null=True)
    finish = models.BooleanField(default=False)
    failure = models.BooleanField(default=False)
    stdout = models.TextField(blank=True, null=True)
    stderr = models.TextField(blank=True, null=True)
    ansible_adhoc = models.ForeignKey(AnsibleAdhoc, models.DO_NOTHING)

    class Meta:
        db_table = 'ansible_adhoc_task'
        unique_together = (('id', 'ansible_adhoc'),)


class AnsibleModule(models.Model):
    module_name = models.CharField(unique=True, max_length=45)
    module_describe = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        db_table = 'ansible_module'
        ordering = ['module_name']

adhoc/views.py
# coding=utf-8
import simplejson
from django.core.paginator import Paginator, PageNotAnInteger, InvalidPage
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.views.generic import TemplateView
from django.views.generic import View
from django.template.loader import render_to_string
from django.template import RequestContext
from django.db.models import Q
from adhoc.models import AnsibleAdhoc, AnsibleModule, AnsibleAdhocTask
from adhoc.tasks import run_adhoc
from host.models import AnsibleGroup, AnsibleHost
from common.utils import playbook_list_hosts, model_to_inventory


# Create your views here.


class AdHocList(LoginRequiredMixin, TemplateView):
    page_size = 10
    page_show_range = 6

    def get(self, request, *args, **kwargs):
        page = request.GET.get('page', 1)
        query = request.GET.get('query', '')

        if query:
            adhocs = AnsibleAdhoc.objects.filter(Q(adhoc_args__contains=query) | Q(adhoc_pattern__contains=query) |
                                                 Q(adhoc_name__contains=query) | Q(id=query))
        else:
            adhocs = AnsibleAdhoc.objects.all()
        paginator = Paginator(adhocs, self.page_size)

        # paginate
        try:
            adhocs = paginator.page(page)
        except PageNotAnInteger:
            adhocs = paginator.page(1)
        except InvalidPage:
            adhocs = paginator.page(paginator.num_pages)

        total_page = paginator.num_pages
        page_show_range = self.page_show_range
        page = int(page)
        if page <= page_show_range:
            page_range = xrange(1, page_show_range + 1)
        elif page_show_range < page <= (total_page - page_show_range):
            page_range = xrange(page - page_show_range / 2, page + page_show_range / 2)
        else:
            page_range = xrange(total_page - page_show_range + 1, total_page + 1)

        res_ctx = {}
        res_ctx.update(page_range=page_range)
        res_ctx.update(adhocs=adhocs)
        res_ctx.update(modules=AnsibleModule.objects.filter(module_name='shell'))

        patterns = []
        patterns.extend([{'name': '[GROUP] %s' % group.group_name, 'value': group.group_name} for group in
                         AnsibleGroup.objects.all()])
        patterns.extend(
            [{'name': '[HOST][%s] %s %s' % (host.ansible_group.group_name, host.hostname, host.ip), 'value': host.ip}
             for host in AnsibleHost.objects.all()])
        patterns.insert(0, {'name': '[ALL]', 'value': 'all'})
        res_ctx.update(patterns=patterns)

        if query:
            res_ctx.update(query=query)

        return render(request, 'adhoc.html', res_ctx)


class AdHocDetail(LoginRequiredMixin, TemplateView):
    def get(self, request, *args, **kwargs):
        adhoc_id = kwargs.get('adhoc_id', 1)
        adhoc = AnsibleAdhoc.objects.select_related().get(id=adhoc_id)
        res_ctx = {}
        try:
            res_ctx.update(adhoc=adhoc)
        except AnsibleAdhoc.DoesNotExist:
            pass
            # 404
        if request.is_ajax():
            if adhoc.finish:
                adhoc_finish = True
            else:
                adhoc_finish = False
            res = render_to_string('adhoc_detail_part.html', res_ctx, context_instance=RequestContext(request))
            return HttpResponse(simplejson.dumps({'result': res, 'status': 0, 'finish': adhoc_finish}),
                                content_type='application/json')

        else:

            return render(request, 'adhoc_detail.html', res_ctx)


class AdhocDelete(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        adhoc_id = request.POST.get('adhoc_id', '')
        if request.is_ajax():
            AnsibleAdhoc.objects.filter(id=adhoc_id).delete()
            return HttpResponse(simplejson({'result': '', 'status': 0}))


class AdhocLog(LoginRequiredMixin, TemplateView):
    def get(self, request, *args, **kwargs):
        adhoc_task_id = request.GET.get('adhoc_task_id', '')
        print adhoc_task_id
        if request.is_ajax():
            try:
                adhoc_task = AnsibleAdhocTask.objects.get(id=adhoc_task_id)
            except:
                pass
                # 404
            res_ctx = {}
            res_ctx.update(log=adhoc_task.stderr if adhoc_task.stderr else adhoc_task.stdout,
                           task_host=adhoc_task.task_host)

            return HttpResponse(simplejson.dumps({'result': res_ctx, 'status': 0}), content_type='application/json')


class AdHocExecute(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        adhoc_name = request.POST.get('adhoc_name', '')
        adhoc_pattern = request.POST.get('adhoc_pattern', '')
        adhoc_args = request.POST.get('adhoc_args', '')
        module_id = request.POST.get('module_id', '')
        adhoc_id = request.POST.get('adhoc_id', '')
        start_time = timezone.now()

        if request.is_ajax():
            adhoc_old = AnsibleAdhoc.objects.get(id=adhoc_id)
            adhoc = AnsibleAdhoc.objects.create(adhoc_name=adhoc_old.adhoc_name, adhoc_pattern=adhoc_old.adhoc_pattern,
                                                adhoc_args=adhoc_old.adhoc_args,
                                                ansible_module=adhoc_old.ansible_module, start_time=start_time,
                                                auth_user_id=request.user.id)

        else:
            adhoc = AnsibleAdhoc.objects.create(adhoc_name=adhoc_name, adhoc_pattern=adhoc_pattern,
                                                adhoc_args=adhoc_args,
                                                ansible_module_id=module_id, start_time=start_time,
                                                auth_user_id=request.user.id)

        inventory_path = model_to_inventory(AnsibleGroup.objects.all())
        # insert adhoc task
        for host in playbook_list_hosts(adhoc.adhoc_pattern, inventory_path):
            AnsibleAdhocTask.objects.create(task_host=host, ansible_adhoc_id=adhoc.id, start_time=timezone.now())

        # use celery to execute an adhoc async
        kwargs = dict(
            instance_type=AnsibleAdhoc.__name__,
            task_id=adhoc.id,
            hosts=adhoc.adhoc_pattern,
            module_args=adhoc.adhoc_args,
            module_name=str(adhoc.ansible_module.module_name),
            inventory_path=inventory_path
        )

        run_adhoc.delay(**kwargs)

        if request.is_ajax():
            res_ctx = {}
            res_ctx.update(adhoc_id=adhoc.id)
            return HttpResponse(simplejson.dumps({'result': res_ctx, 'status': 0, 'finish': adhoc.finish}),
                                content_type='application/json')
        else:
            return HttpResponseRedirect('/adhoc/%d' % adhoc.id)

job/views.py
from __future__ import division
import simplejson
from django.shortcuts import render, HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, InvalidPage
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import render_to_string
from django.template import RequestContext
from django.views.generic import TemplateView, View
from job.models import AnsibleJob, AnsibleJobTask
from playbook.models import AnsiblePlaybook
from host.models import AnsibleGroup,AnsibleHost
from common.utils import playbook_list_hosts, playbook_generate_yaml,model_to_inventory
from tasks import run_job


# Create your views here.


class AnsibleJobList(LoginRequiredMixin,TemplateView):
    page_size = 10
    page_show_range = 6

    def get(self, request, *args, **kwargs):
        page = request.GET.get('page', 1)
        query = request.GET.get('query', '')

        if query:
            jobs = AnsibleJob.objects.filter(Q(job_name__contains=query) | Q(job_pattern__contains=query))
        else:
            jobs = AnsibleJob.objects.all()
        paginator = Paginator(jobs, self.page_size)

        # paginate
        try:
            jobs = paginator.page(page)
        except PageNotAnInteger:
            jobs = paginator.page(1)
        except InvalidPage:
            jobs = paginator.page(paginator.num_pages)

        total_page = paginator.num_pages
        page_show_range = self.page_show_range
        page = int(page)
        if page <= page_show_range:
            page_range = xrange(1, page_show_range + 1)
        elif page_show_range < page <= (total_page - page_show_range):
            page_range = xrange(page - page_show_range / 2, page + page_show_range / 2)
        else:
            page_range = xrange(total_page - page_show_range + 1, total_page + 1)

        res_ctx = {}
        res_ctx.update(page_range=page_range)
        res_ctx.update(jobs=jobs)
        res_ctx.update(templates=AnsiblePlaybook.objects.all())

        patterns = []
        patterns.extend([{'name':'[GROUP] %s'%group.group_name,'value':group.group_name} for group in AnsibleGroup.objects.all()])
        patterns.extend([{'name':'[HOST][%s] %s %s '%(host.ansible_group.group_name,host.hostname,host.ip),'value':host.ip} for host in AnsibleHost.objects.all()])
        patterns.insert(0,{'name':'[ALL]','value':'all'})
        res_ctx.update(patterns=patterns)

        if query:
            res_ctx.update(query=query)

        return render(request, 'job.html', res_ctx)


class AnsibleJobDetail(LoginRequiredMixin,TemplateView):
    def get(self, request, *args, **kwargs):
        job_id = kwargs.get('job_id', 1)
        res_ctx = {}
        try:

            job = AnsibleJob.objects.select_related().get(id=job_id)
        except AnsibleJob.DoesNotExist:
            pass
            # 404

        res_ctx.update(job=job)

        host_status = []
        hosts = set([task.task_host for task in AnsibleJobTask.objects.filter(ansible_job_id=job.id)])
        for host in hosts:
            # compute progress bar
            all_tasks = AnsibleJobTask.objects.filter(ansible_job_id=job_id, task_host=host)
            finished_tasks = set([task for task in all_tasks if task.finish == True])
            progress_percent = int(len(finished_tasks) / all_tasks.count() * 100)

            # get running task
            if all_tasks.count() != len(finished_tasks):
                processing_task = all_tasks.filter(finish=False).first()
                processing_index = len(finished_tasks) + 1
            else:
                processing_index = None
                processing_task = None

            # get start_time and end_time
            if all_tasks.count() > 0:
                start_time = all_tasks.first().start_time
                if job.finish:
                    end_time = all_tasks.last().end_time
                else:
                    end_time = None

            host_status.append(
                dict(
                    ip=host,
                    progress_percent=progress_percent,
                    start_time=start_time,
                    end_time=end_time,
                    processing_index=processing_index,
                    processing_task=processing_task,
                    all=all_tasks.count(),
                    success=all_tasks.filter(failure=False, finish=True).count()
                )
            )

        res_ctx.update(hosts=host_status)

        if request.is_ajax():
            if job.finish:
                job_finish = True
            else:
                job_finish = False
            res = render_to_string('job_detail_part.html', res_ctx, context_instance=RequestContext(request))
            return HttpResponse(simplejson.dumps({'result': res, 'status': 0, 'finish': job_finish}),
                                content_type='application/json')

        else:

            return render(request, 'job_detail.html', res_ctx)


class AnsibleJobLog(LoginRequiredMixin,TemplateView):
    def get(self, request, *args, **kwargs):
        job_id = request.GET.get('job_id', '')
        host = request.GET.get('host', '')
        job_tasks = AnsibleJobTask.objects.filter(ansible_job_id=job_id, task_host=host)
        res_ctx = {}
        res_ctx.update(job_tasks=job_tasks)
        res = render_to_string('job_detail_log.html', res_ctx, context_instance=RequestContext(request))
        return HttpResponse(simplejson.dumps({'result': res, 'status': 0, 'host': host}),
                            content_type='application/json')


class AnsibleJobExecuete(LoginRequiredMixin,View):
    def post(self, request, *args, **kwargs):
        job_name = request.POST.get('job_name', '')
        job_pattern = request.POST.get('job_pattern', '')
        template_id = request.POST.get('template_id', '')
        start_time = timezone.now()

        if request.is_ajax():
            pass
        else:
            job = AnsibleJob.objects.create(job_name=job_name, job_pattern=job_pattern, start_time=start_time,
                                            ansible_playbook_id=template_id,auth_user_id=request.user.id)
            for host in playbook_list_hosts(job.job_pattern):
                AnsibleJobTask.objects.bulk_create([
                                                       AnsibleJobTask(task_name=task.task_name,
                                                                      task_host=host,
                                                                      ansible_job_id=job.id,
                                                                      start_time=start_time)
                                                       for task in
                                                       job.ansible_playbook.ansibleplaybooktask_set.all()
                                                       ]
                                                   )

        inventory_path = model_to_inventory(AnsibleGroup.objects.all())
        playbook_template = AnsiblePlaybook.objects.get(id=template_id)
        kwargs = dict(
            instance_type=AnsibleJob.__name__,
            task_id=job.id,
            hosts=job.job_pattern,
            inventory_path=inventory_path
        )

        run_job.delay(playbook_generate_yaml(playbook_template), **kwargs)
        return HttpResponseRedirect('/job/%d' % job.id)

templates/adhoc.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/css/adhoc.css">
{% endblock %}


{% block content %}
    <div class="container search-container">
        <div class="input-group">
            <span class="input-group-addon"><i class="fa fa-search"></i></span>
            <form action="{% url 'adhoc_list' %}" method="get">
                <input class="form-control" type="text" placeholder="search" name="query" value="{% if query %}{{ query }}{% endif %}">
            </form>



            <button class="btn btn-primary" data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i>
            </button>
        </div>

    </div>

    <div class="container">
        <table class="table table-striped adhoc-table ">
            <thead>
            <tr>
                <th width="10%">Name</th>
                <th width="10%"><i class="fa fa-laptop fa-lg"></i> Pattern</th>
                <th width="10%"><i class="fa fa-cubes fa-lg"></i> Module</th>
                <th width="30%"><i class="fa fa-location-arrow fa-lg"></i> Args</th>
                 <th width="10%"><i class="fa fa-user fa-lg"></i> By who</th>
                <th width="20%"><i class="fa fa-clock-o fa-lg"></i> Start time</th>
                <th width="10%"><i class="fa fa-gears fa-lg"></i> Operation</th>
            </tr>
            </thead>
            <tbody>
            {% for adhoc in adhocs %}
                <tr>
                    <td>{{ adhoc.adhoc_name }}</td>
                    <td>{{ adhoc.adhoc_pattern }}</td>
                    <td>{{ adhoc.ansible_module.module_name }}</td>
                    <td>{{ adhoc.adhoc_args }}</td>
                    <td>{{ adhoc.auth_user.username }}</td>
                    <td>{{ adhoc.start_time|date:"Y-m-d G:i:s" }}</td>
                    <td>
                        <a class="ops-link" href="{% url 'adhoc_list' %}{{ adhoc.id }}"><i
                                class="fa fa-file fa-lg "></i></a>
{#                        <a class="ops-link retry" href="javascript:void(0)" adhoc_id="{{ adhoc.id }}"><i#}
{#                                class="fa fa-repeat"></i></a>#}
                        <a class="ops-link" href="javascript:void(0)"><i class="fa fa-trash fa-lg"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

    {% if adhocs.paginator.num_pages > 1 %}
    <nav class="page">
        <ul class="pagination">
            {% if adhocs.has_previous %}
                <li class=""><a
                        href="/adhoc/?page={{ adhocs.previous_page_number }}{% if query %}&query={{ query }}{% endif %}"
                        aria-label="Previous"><span aria-hidden="true">prev</span></a></li>
            {% endif %}
            {% for i in page_range %}
                <li class="{% if adhocs.number == i %}active{% endif %}"><a
                        href="/adhoc/?page={{ i }}{% if query %}&query={{ query }}{% endif %}">{{ i }}<span
                        class="sr-only">(current)</span></a>
                </li>
            {% endfor %}
            {% if adhocs.has_next %}
                <li class="">
                    <a href="/adhoc/?page={{ adhocs.next_page_number }}{% if query %}&query={{ query }}{% endif %}"
                       aria-label="Next">
                        <span aria-hidden="true">next</span></a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}


    <!-- Button trigger modal -->

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">New Command</h4>
                </div>
                <form class="form-horizontal" action="{% url 'adhoc_add' %}" method="post">
                    {% csrf_token %}
                    <div class="modal-body">

                        <div class="form-group">
                            <label class="col-sm-2 control-label">name</label>

                            <div class="col-sm-8">
                                <input class="form-control" name="adhoc_name">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">pattern</label>

                            <div class="col-sm-8">
                                <select class="form-control" name="adhoc_pattern">
                                    {% for pattern in patterns %}
                                    <option value="{{ pattern.value }}">{{ pattern.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">module</label>

                            <div class="col-sm-8">
                                <select class="form-control" name="module_id">
                                    {% for module in modules %}
                                        <option value="{{ module.id }}">{{ module.module_name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-2 control-label">args</label>

                            <div class="col-sm-8">
                                <input class="form-control" name="adhoc_args">
                            </div>
                        </div>


                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Run</button>
                    </div>
                </form>
            </div>
        </div>

    </div>


{% endblock %}

{% block script %}
    <script type="text/javascript" src="/static/js/adhoc.js"></script>
    <script>
        var adhoc_add = "{% url 'adhoc_add' %}";
        $(function () {
            Adhoc.init();
        })
    </script>
{% endblock %}

templates/adhoc_detail.html
{% extends 'base.html' %}

{% block css %}
    <link rel="stylesheet" href="/static/css/adhoc_detail.css">
{% endblock %}


{% block content %}
    <div class="container">
        <ol class="breadcrumb">
            <li>Adhoc</li>
            <li>Detail</li>
        </ol>
    </div>

    <div class="container">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title"><i class="fa fa-tasks"></i> {{ adhoc.adhoc_name }}</h4>
            </div>
            <div class="panel-body">


                <div class="panel panel-default command-info">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h3 class="panel-title"><i class="fa fa-info"></i> Info</h3>
                    </div>
                    <div class="panel-body">
                        <form class="form-horizontal">
                            <div class="form-group">
                                <label class="col-sm-2">pattern</label>

                                {{ adhoc.adhoc_pattern }}
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2">module</label>
                                {{ adhoc.ansible_module.module_name }}
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2">args</label>

                                {{ adhoc.adhoc_args }}
                            </div>

                        </form>
                    </div>
                </div>
                <div class="panel panel-default host-info">
                    <div class="panel-heading" role="tab" id="headingTwo">
                        <h3 class="panel-title" id="hosts_heading"><i class="fa fa-desktop"></i> Hosts <i
                                class="fa fa-spinner fa-spin "></i></h3>

                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingTwo">
                        <div class="panel-body">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <td width="25%">ip</td>
                                    <td width="25%">start time</td>
                                    <td width="25%">end time</td>
                                    <td width="15%">status</td>
                                    <td width="10%">log</td>
                                </tr>
                                </thead>
                                <tbody id="hosts_body" task_id="{{ adhoc.id }}">
                                {% for task  in adhoc.ansibleadhoctask_set.all %}
                                    <tr>
                                        <td>{{ task.task_host }}</td>
                                        <td>{{ task.start_time|date:"Y-m-d G:i:s" }}</td>
                                        <td>{{ task.end_time|date:"Y-m-d G:i:s" }}</td>
                                        <td>
                                            {% if task.finish == True%}
                                                {% if task.failure == True %}
                                                    <i class="fa fa-circle fa-lg status-fail"></i>
                                                {% else %}
                                                    <i class="fa fa-circle fa-lg status-success"></i>
                                                {% endif %}

                                            {% else %}
                                                <i class="fa fa-circle fa-lg status-process"></i>
                                            {% endif %}

                                        </td>
                                        <td>
                                            <a class="task-log" href="#" data-toggle="modal" data-target="#myModal"
                                               adhoc_task_id="{{ task.id }}"><i
                                                    class="fa fa-search-plus fa-lg"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    {#    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">#}

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content log-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="log-title"></h4>
                </div>
                <div class="modal-body">

                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h3 class="panel-title">log</h3>
                        </div>
                        <div class="panel-body log-body">
                            <pre class="log-pre" id="stdout"></pre>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block script %}
    <script type="text/javascript" src="/static/js/adhoc_detail.js"></script>
    <script>
        var adhoc_log = "{% url 'adhoc_log' %}"
        $(function () {
            AdhocDetail.init()
        })
    </script>
{% endblock %}

templates/adhoc_detail_part.html
{% for task  in adhoc.ansibleadhoctask_set.all %}
    <tr>
        <td>{{ task.task_host }}</td>
        <td>{{ task.start_time|date:"Y-m-d G:i:s" }}</td>
        <td>{{ task.end_time|date:"Y-m-d G:i:s" }}</td>
        <td>
            {% if task.finish == True %}
                {% if task.failure == True %}
                    <i class="fa fa-circle fa-lg status-fail"></i>
                {% else %}
                    <i class="fa fa-circle fa-lg  status-success"></i>
                {% endif %}

            {% else %}
                <i class="fa fa-circle fa-lg status-process"></i>
            {% endif %}
        </td>
        <td>
            <a class="task-log" href="#" data-toggle="modal" data-target="#myModal" adhoc_task_id="{{ task.id }}"><i
                    class="fa fa-search-plus fa-lg"></i></a>
        </td>
    </tr>
{% endfor %}

templates/job_detail_log.html
<thead>
<td width="35%">Task name</td>
<td width="5%">Status</td>
<td width="60%">Log</td>
</thead>
<tbody>
{% for task in job_tasks %}
    <tr>
        <td>{{ task.task_name }}</td>
        <td style="text-align: center">
            {% if task.failure %}
                <i class="fa fa-circle fa-lg status-fail"></i>
            {% else %}
                <i class="fa fa-circle fa-lg status-success"></i>
            {% endif %}
        </td>
        <td>
            <div class="log-div">
                {% if task.stdout or task.stderr %}
                <pre class="log-pre">{% if task.stdout %}{{ task.stdout }}{% else %}{{ task.stderr }}{% endif %}</pre>
                {% endif %}
            </div>

        </td>
    </tr>
{% endfor %}
</tbody>